#!/bin/bash

if [[ -n "${1}" ]]; then
    export AWS_PROFILE="${1}"
    export AWS_DEFAULT_PROFILE="${1}"
    export AWS_REGION="us-east-1"
    export AWS_DEFAULT_REGION="us-east-1"
fi

export AWS_ACCESS_KEY_ID="$(aws configure get aws_access_key_id --profile $AWS_PROFILE)"
export AWS_SECRET_ACCESS_KEY="$(aws configure get aws_secret_access_key --profile $AWS_PROFILE)"
export AWS_SESSION_TOKEN="$(aws configure get aws_session_token --profile $AWS_PROFILE)"
