# .bashrc

. "${HOME}/.dotfiles-path"

# load scripts
if [[ -z "${BASH_FIRST}" ]] && [[ -f ~/.bash_profile ]]; then
	export BASH_FIRST="no"
        . "${HOME}/.bash_profile"
else
	. "${DOTFILES_PATH}/loader/william"
	unset BASH_FIRST
fi

# Source global definitions
#[[ -f /etc/bashrc ]] && . /etc/bashrc


. "$HOME/.cargo/env"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
