# .bash_profile

# if rc is null, and first is null, load other
if [[ -z "${BASH_FIRST}" ]] && [[ -f ~/.bashrc ]]; then
	export BASH_FIRST="no"
	. ~/.bashrc
else
	. ~/dotfiles/loader/william
	unset BASH_FIRST
fi

