# .bashrc

# load scripts
if [[ -z "${BASH_FIRST}" ]] && [[ -f ~/.bash_profile ]]; then
	export BASH_FIRST="no"
    . ~/.bash_profile
else
	. ~/dotfiles/loader/william
	unset BASH_FIRST
fi

# Source global definitions
#[[ -f /etc/bashrc ]] && . /etc/bashrc

