#!/bin/bash

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
export SONAR_TOKEN="squ_52a000cc0d384c2104b5310da0cd9c8e012085be"


# colors
export TERM='xterm-256color'
export CLICOLOR=1
export COLORTERM="truecolor"

#export LANG=en_US.UTF-8
#export LC_CTYPE=en_US.UTF-8

# AWS
export REGION='us-east-1'
export ACCOUNT='ndsdev'
export AWS_PROFILE="${ACCOUNT}"
export AWS_DEFAULT_PROFILE="${ACCOUNT}"
export AWS_DEFAULT_REGION="${REGION}"

# User specific environment and startup programs
export PATH="${PATH}:${HOME}/.local/bin:${HOME}/.bin:${HOME}/bin:/usr/local/bin"
# export LD_LIBRARY_PATH="/usr/local/openssl/lib:${LD_LIBRARY_PATH}"
# . /home/ndsadmin/.macbook-setup/mc-laptop-env.sh
# export PODMAN_IGNORE_CGROUPSV1_WARNING="true"

export RUBYOPT='-W:no-deprecated -W:no-experimental'

code_result="$(which code 2>&1)"
if [[ "${code_result}" != *"which: no "* ]]; then
  export SUDO_EDITOR="${code_result} -w"
fi

# User specific environment and startup programs
source "$HOME/.cargo/env"

# curl -sSL https://get.rvm.io | bash -s stable
# rvm install 3.4.2
# rvm use 3.4.2 --default
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="$PATH:$HOME/.rvm/bin"

# wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
# sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
export PATH="$PATH:/usr/local/go/bin"

# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init -)"

# eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# export PATH="${PATH}:${HOME}/.nix-profile/bin"
# export LOCALE_ARCHIVE="$(nix-env --installed --no-name --out-path --query glibc-locales)/lib/locale/locale-archive"
# /nix/store/k23afqb8da5s4283pai9zzvrnh4bvg9n-glibc-locales-2.38-27

# export PATH="$(npm config get prefix)/bin:$PATH"

# . $HOME/.asdf/asdf.sh

# If not ZSH, so probably bash, load these
# if [[ -z $ZSH_STARTING ]]; then
#     . $HOME/.asdf/completions/asdf.bash
#     #source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/bashrc"
# fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# If ZSH, then load these
if [[ $ZSH_STARTING == "true" ]]; then
    #source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
    unset ZSH_STARTING
    DISABLE_UPDATE_PROMPT=true
    alias shopt="echo"
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    HISTFILE=~/.histfile
    HISTSIZE=100000000000
    SAVEHIST=100000000000
    ZSH_COLORIZE_STYLE="colorful"
    ZSH_THEME="powerlevel10k/powerlevel10k"

    #source ~/powerlevel10k/powerlevel10k.zsh-theme
    source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
    source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

    # Path to your oh-my-zsh installation.
    export ZSH="$HOME/.oh-my-zsh"
    # Uncomment the following line to use case-sensitive completion.
    # CASE_SENSITIVE="true"

    # Uncomment the following line to use hyphen-insensitive completion.
    # Case-sensitive completion must be off. _ and - will be interchangeable.
    # HYPHEN_INSENSITIVE="true"

    # Uncomment one of the following lines to change the auto-update behavior
    # zstyle ':omz:update' mode disabled  # disable automatic updates
    # zstyle ':omz:update' mode auto      # update automatically without asking
    # zstyle ':omz:update' mode reminder  # just remind me to update when it's time

    # Uncomment the following line to change how often to auto-update (in days).
    # zstyle ':omz:update' frequency 13

    # Which plugins would you like to load?
    # Standard plugins can be found in $ZSH/plugins/
    # Custom plugins may be added to $ZSH_CUSTOM/plugins/
    # Example format: plugins=(rails git textmate ruby lighthouse)
    # Add wisely, as too many plugins slow down shell startup.
    plugins=(git)
    source $ZSH/oh-my-zsh.sh

    # End of lines configured by zsh-newuser-install
    # The following lines were added by compinstall
    zstyle :compinstall filename "${HOME}/.zshrc"

    # append completions to fpath
    # fpath=(${ASDF_DIR}/completions $fpath)

    # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
    # Initialization code that may require console input (password prompts, [y/n]
    # confirmations, etc.) must go above this block; everything else may go below.
    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
      source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    fi

    # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

    # initialise completions with ZSH's compinit
    autoload -Uz compinit && compinit

    #source ~/.zplug/init.zsh
    #zplug "so-fancy/diff-so-fancy", as:command, use:bin/git-dsf

fi

# vscode helper
[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path $(readlink /proc/$$/exe | sed "s/.*\///"))"
export GH_PAGER=""

# clean PATH
export PATH=$(echo "$PATH" | awk -v RS=: -v ORS=: '!seen[$0]++' | sed 's/:$//; s/^://; s/::*/:/g')

#init_docker
#init_nginx

