#!/bin/bash

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# colors
export TERM='xterm-256color'
export CLICOLOR=1

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# User specific environment and startup programs
PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH

export RUBYOPT='-W:no-deprecated -W:no-experimental'

#eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

#. /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

