#!/bin/bash

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
export SONAR_TOKEN="squ_52a000cc0d384c2104b5310da0cd9c8e012085be"

# colors
export TERM='xterm-256color'
export CLICOLOR=1
export COLORTERM="truecolor"

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# AWS
export REGION='us-east-1'
export ACCOUNT='ndsdev'
export AWS_PROFILE="${ACCOUNT}"
export AWS_DEFAULT_PROFILE="${ACCOUNT}"
export AWS_DEFAULT_REGION="${REGION}"

# User specific environment and startup programs
export PATH="${PATH}:${HOME}/.local/bin:${HOME}/.bin:${HOME}/bin:/usr/local/bin"
# export LD_LIBRARY_PATH="/usr/local/openssl/lib:${LD_LIBRARY_PATH}"
# . /home/ndsadmin/.macbook-setup/mc-laptop-env.sh
# export PODMAN_IGNORE_CGROUPSV1_WARNING="true"

export RUBYOPT='-W:no-deprecated -W:no-experimental'

code_result="$(which code 2>&1)"
if [[ "${code_result}" != *"which: no "* ]]; then
  export SUDO_EDITOR="${code_result} -w"
fi

# User specific environment and startup programs
source "$HOME/.cargo/env"

# curl -sSL https://get.rvm.io | bash -s stable
# rvm install 3.4.2
# rvm use 3.4.2 --default
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
#export PATH="$PATH:$HOME/.rvm/bin"
#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# somehow rvm is forcing its presence
unset GEM_HOME GEM_PATH MY_RUBY_HOME
export PATH=$(echo $PATH | sed -e 's/:\/home\/ndsadmin\/.rvm[^:]*//g' -e 's/^\/home\/ndsadmin\/.rvm[^:]*://g')

# wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
# sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
export PATH="$PATH:/usr/local/go/bin"

# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init -)"

# handling brew through functions to avoid issues with sudo and root user
# eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/Homebrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/Homebrew/sbin${PATH+:$PATH}";
[ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}";
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";

# export PATH="${PATH}:${HOME}/.nix-profile/bin"
# export LOCALE_ARCHIVE="$(nix-env --installed --no-name --out-path --query glibc-locales)/lib/locale/locale-archive"
# /nix/store/k23afqb8da5s4283pai9zzvrnh4bvg9n-glibc-locales-2.38-27

# export PATH="$(npm config get prefix)/bin:$PATH"

# . $HOME/.asdf/asdf.sh

# If not ZSH, so probably bash, load these
# if [[ -z $ZSH_STARTING ]]; then
#     . $HOME/.asdf/completions/asdf.bash
#     #source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/bashrc"
# fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# ONLY load bash_completion if we are actually in Bash

if [[ -n "$BASH_VERSION" ]]; then
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

    shopt -s autocd
    shopt -s cdable_vars

    cd() {
      builtin pushd "$@" > /dev/null || return
    }

    back() {
      builtin cd -
    }

    prevdir() {
      builtin pushd +1 > /dev/null || return
    }

    nextdir() {
      builtin pushd -0 > /dev/null || return
    }

    alias ..='cd ..'
    alias ...='cd ../..'
    alias ....='cd ../../..'
    alias d='dirs -v'
fi

# If ZSH, then load these
if [[ -n "${ZSH_VERSION}" ]]; then

    #source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
    DISABLE_UPDATE_PROMPT=true
    # alias shopt="echo"
    #export LC_ALL=en_US.UTF-8
    #export LANG=en_US.UTF-8
    HISTFILE=~/.histfile
    HISTSIZE=100000000000
    SAVEHIST=100000000000
    ZSH_COLORIZE_STYLE="colorful"
    #ZSH_THEME="powerlevel10k/powerlevel10k"
    export ZSH_THEME=""

    #source ~/powerlevel10k/powerlevel10k.zsh-theme
    source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
    source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

    # Path to your oh-my-zsh installation.
    export ZSH="$HOME/.oh-my-zsh"
    # Uncomment the following line to use case-sensitive completion.
    # CASE_SENSITIVE="true"

    setopt AUTO_CD
    setopt CDABLE_VARS
    setopt AUTO_PUSHD
    setopt PUSHD_IGNORE_DUPS
    setopt PUSHD_SILENT
    dirs -v > /dev/null 2>&1

    alias back='cd -'
    alias prev='pushd +1'
    alias dirs='dirs -v'

    prevdir() # Go back to the previous directory in the stack
    {
      pushd +1 > /dev/null
    }

    nextdir() # Go forward to the next directory in the stack
    {
      pushd -0 > /dev/null
    }

    # Uncomment the following line to use hyphen-insensitive completion.
    # Case-sensitive completion must be off. _ and - will be interchangeable.
    # HYPHEN_INSENSITIVE="true"

    # Uncomment one of the following lines to change the auto-update behavior
    # zstyle ':omz:update' mode disabled  # disable automatic updates
    # zstyle ':omz:update' mode auto      # update automatically without asking
    # zstyle ':omz:update' mode reminder  # just remind me to update when it's time

    # Uncomment the following line to change how often to auto-update (in days).
    # zstyle ':omz:update' frequency 13

    # Which plugins would you like to load?
    # Standard plugins can be found in $ZSH/plugins/
    # Custom plugins may be added to $ZSH_CUSTOM/plugins/
    # Example format: plugins=(rails git textmate ruby lighthouse)
    # Add wisely, as too many plugins slow down shell startup.
    source <(fzf --zsh)
    plugins=(git git-escape-magic command-not-found salt composer sudo gradle zsh-navigation-tools zsh-interactive-cd)
    # plugins=(git colored-man-pages colorize command-not-found composer dnf git-escape-magic gitignore gradle node python pylint salt sudo systemd yarn zsh-navigation-tools zsh-interactive-cd)
    source $ZSH/oh-my-zsh.sh

    # End of lines configured by zsh-newuser-install
    # The following lines were added by compinstall
    zstyle :compinstall filename "${HOME}/.zshrc"

    export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE="20"
    export ZSH_AUTOSUGGEST_USE_ASYNC=1

    _complete_alias() {
        [[ -n $PREFIX ]] && compadd -- ${(M)${(k)galiases}:#$PREFIX*}
        return 1
    }
    zstyle ':completion:*' completer _complete_alias _complete _ignored

    # append completions to fpath
    # fpath=(${ASDF_DIR}/completions $fpath)

    # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
    # Initialization code that may require console input (password prompts, [y/n]
    # confirmations, etc.) must go above this block; everything else may go below.
    #if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    #  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    #fi

    # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
    #[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

    # initialise completions with ZSH's compinit
    autoload -Uz compinit && compinit

    # Initialize Oh My Posh (Takes over the prompt from Oh My Zsh)
    source $HOME/.dotfiles/home/omp/helper

    if [[ "$POSH_PLAIN" == "1" ]]; then
      eval "$(oh-my-posh init zsh --config $DOTFILES_PATH/home/omp/plain.yaml)"
    else
      eval "$(oh-my-posh init zsh --config "$DOTFILES_PATH/home/omp/final.yaml")"
    fi

    ### ZNT's installer added snippet ###
    fpath=( "$fpath[@]" "$HOME/.config/znt/zsh-navigation-tools" )
    autoload n-aliases n-cd n-env n-functions n-history n-kill n-list n-list-draw n-list-input n-options n-panelize n-help
    autoload znt-usetty-wrapper znt-history-widget znt-cd-widget znt-kill-widget
    alias naliases=n-aliases ncd=n-cd nenv=n-env nfunctions=n-functions nhistory=n-history
    alias nkill=n-kill noptions=n-options npanelize=n-panelize nhelp=n-help
    zle -N znt-history-widget
    bindkey '^R' znt-history-widget
    setopt AUTO_PUSHD HIST_IGNORE_DUPS PUSHD_IGNORE_DUPS
    zstyle ':completion::complete:n-kill::bits' matcher 'r:|=** l:|=*'
    ### END ###

    #source ~/.zplug/init.zsh
    #zplug "so-fancy/diff-so-fancy", as:command, use:bin/git-dsf
fi

# vscode helper
[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path $(readlink /proc/$$/exe | sed "s/.*\///"))"
export GH_PAGER=""

#init_docker
#init_nginx

